// ============================================================================
// Oracle & Price Feed — Core Types
// ============================================================================

/** Supported external price data sources */
export type OracleSourceType = 'CoinGecko' | 'Binance' | 'ManualNAV' | 'TIFA';

/** Raw price from a single source before aggregation */
export interface RawPrice {
  asset: string;
  price: number;
  source: OracleSourceType;
  timestamp: number; // epoch ms
  confidence: number; // 0-1
}

/** Aggregated price after median calculation across sources */
export interface AggregatedPrice {
  asset: string;
  medianPrice: number;
  sources: RawPrice[];
  twap: TWAPData | null;
  confidence: number;
  timestamp: number;
}

/** Circuit breaker state for a single asset */
export interface CircuitBreakerState {
  asset: string;
  isTripped: boolean;
  reason: string | null;
  trippedAt: number | null; // epoch ms
  recoversAt: number | null; // epoch ms
  lastValidPrice: number | null;
}

/** TWAP (Time-Weighted Average Price) data */
export interface TWAPData {
  price5m: number | null;
  price15m: number | null;
  price1h: number | null;
  sampleCount: number;
  lastSampleTs: number;
}

/** TWAP sample point */
export interface TWAPSample {
  price: number;
  timestamp: number; // epoch ms
}

/** Status of a single source adapter */
export interface SourceStatus {
  source: OracleSourceType;
  isConnected: boolean;
  lastFetchTs: number | null;
  lastError: string | null;
  assetCount: number;
}

/** Overall oracle pipeline status */
export interface OracleStatus {
  sourceStatuses: SourceStatus[];
  aggregatedPrices: AggregatedPrice[];
  circuitBreakers: CircuitBreakerState[];
  lastCycleTs: number | null;
  lastCycleDurationMs: number | null;
  isHealthy: boolean;
}

/** Alert generated by oracle pipeline (circuit breaker trips, source failures, etc.) */
export interface OracleAlert {
  id: string;
  type: 'circuit_breaker_trip' | 'circuit_breaker_recover' | 'source_failure' | 'source_recovery' | 'stale_price';
  asset: string | null;
  message: string;
  severity: 'info' | 'warning' | 'critical';
  metadata: Record<string, unknown>;
  timestamp: number;
}

/** Asset symbol to CoinGecko ID mapping */
export const COINGECKO_ID_MAP: Record<string, string> = {
  BTC: 'bitcoin',
  wBTC: 'bitcoin',
  ETH: 'ethereum',
  USDC: 'usd-coin',
  USDT: 'tether',
  // CC and DUAL have no CoinGecko listing — priced via TIFA internal feed
};

/** Asset symbol to Binance trade symbol mapping */
export const BINANCE_SYMBOL_MAP: Record<string, string> = {
  BTC: 'btcusdt',
  wBTC: 'btcusdt',
  ETH: 'ethusdt',
  USDC: 'usdcusdt',
  USDT: 'usdcusdt', // reverse proxy
};

/** Reverse Binance symbol → our asset symbol */
export const BINANCE_REVERSE_MAP: Record<string, string> = {
  btcusdt: 'BTC',
  ethusdt: 'ETH',
  usdcusdt: 'USDC',
};

/** Manual NAV default prices for RWA assets */
export const DEFAULT_NAV_PRICES: Record<string, number> = {
  'T-BILL-2026': 99.87,
  'SPY-2026': 512.45,
  'US-T10Y': 96.45,
  'T-BILL': 1.0,
};

/** TIFA internal feed prices (tokens without public market listings) */
export const DEFAULT_TIFA_PRICES: Record<string, number> = {
  DUAL: 2.45,
  CC: 1.00, // Canton Coin — devnet price, updateable via POST /oracle/manual/CC
};

/** Supported oracle assets (union of all sources) */
export const ORACLE_ASSETS = [
  'BTC', 'wBTC', 'ETH', 'USDC', 'USDT',
  'T-BILL-2026', 'SPY-2026', 'US-T10Y', 'T-BILL',
  'DUAL', 'CC',
] as const;

export type OracleAsset = (typeof ORACLE_ASSETS)[number];
