export const ENDPOINTS = {
  POOLS: '/pools',
  POOL_DETAIL: (id: string) => `/pools/${id}`,
  POOL_HISTORY: (id: string) => `/pools/${id}/history`,
  POOL_DEPOSIT: (id: string) => `/pools/${id}/deposit`,
  POOL_WITHDRAW: (id: string) => `/pools/${id}/withdraw`,
  BORROW_REQUEST: '/borrow/request',
  BORROW_POSITIONS: '/borrow/positions',
  BORROW_REPAY: (id: string) => `/borrow/positions/${id}/repay`,
  BORROW_ADD_COLLATERAL: (id: string) => `/borrow/positions/${id}/add-collateral`,
  SEC_LENDING_OFFERS: '/sec-lending/offers',
  SEC_LENDING_ACCEPT: (id: string) => `/sec-lending/offers/${id}/accept`,
  SEC_LENDING_DEALS: '/sec-lending/deals',
  SEC_LENDING_RECALL: (id: string) => `/sec-lending/deals/${id}/recall`,
  SEC_LENDING_RETURN: (id: string) => `/sec-lending/deals/${id}/return`,
  CREDIT_SCORE: '/credit/score',
  CREDIT_HISTORY: '/credit/history',
  ORACLE_PRICES: '/oracle/prices',
  ORACLE_PRICE: (asset: string) => `/oracle/prices/${asset}`,
  GOVERNANCE_PROPOSALS: '/governance/proposals',
  GOVERNANCE_VOTE: (id: string) => `/governance/proposals/${id}/vote`,
  FLASH_LOAN_EXECUTE: '/flash-loan/execute',
  STAKING_INFO: '/staking/info',
  STAKING_POSITION: '/staking/position',
  STAKING_STAKE: '/staking/stake',
  STAKING_UNSTAKE: '/staking/unstake',
  STAKING_CLAIM: '/staking/claim',
  ANALYTICS_OVERVIEW: '/analytics/overview',
  ANALYTICS_HISTORY: '/analytics/history',
  ADMIN_PAUSE: '/admin/pause',
  ADMIN_RESUME: '/admin/resume',
  ADMIN_CONFIG: '/admin/config',
} as const;
