export const ENDPOINTS = {
  POOLS: '/pools',
  POOL_DETAIL: (id: string) => `/pools/${id}`,
  POOL_HISTORY: (id: string) => `/pools/${id}/history`,
  POOL_DEPOSIT: (id: string) => `/pools/${id}/deposit`,
  POOL_WITHDRAW: (id: string) => `/pools/${id}/withdraw`,
  BORROW_REQUEST: '/borrow/request',
  BORROW_POSITIONS: '/borrow/positions',
  BORROW_REPAY: (id: string) => `/borrow/positions/${id}/repay`,
  BORROW_ADD_COLLATERAL: (id: string) => `/borrow/positions/${id}/add-collateral`,
  SEC_LENDING_OFFERS: '/sec-lending/offers',
  SEC_LENDING_ACCEPT: (id: string) => `/sec-lending/offers/${id}/accept`,
  SEC_LENDING_DEALS: '/sec-lending/deals',
  SEC_LENDING_RECALL: (id: string) => `/sec-lending/deals/${id}/recall`,
  SEC_LENDING_RETURN: (id: string) => `/sec-lending/deals/${id}/return`,
  CREDIT_SCORE: '/credit/score',
  CREDIT_HISTORY: '/credit/history',
  ORACLE_PRICES: '/oracle/prices',
  ORACLE_PRICE: (asset: string) => `/oracle/prices/${asset}`,
  GOVERNANCE_CONFIG: '/governance/config',
  GOVERNANCE_PROPOSALS: '/governance/proposals',
  GOVERNANCE_PROPOSAL_DETAIL: (id: string) => `/governance/proposals/${id}`,
  GOVERNANCE_PROPOSAL_CANCEL: (id: string) => `/governance/proposals/${id}/cancel`,
  GOVERNANCE_VOTE: (id: string) => `/governance/proposals/${id}/vote`,
  GOVERNANCE_VOTES: (id: string) => `/governance/proposals/${id}/votes`,
  GOVERNANCE_MY_VOTE: (id: string) => `/governance/proposals/${id}/my-vote`,
  GOVERNANCE_VETO: (id: string) => `/governance/proposals/${id}/veto`,
  GOVERNANCE_EXECUTE: (id: string) => `/governance/proposals/${id}/execute`,
  GOVERNANCE_DELEGATE: '/governance/delegate',
  GOVERNANCE_UNDELEGATE: '/governance/undelegate',
  GOVERNANCE_DELEGATIONS: '/governance/delegations',
  GOVERNANCE_VOTING_POWER: '/governance/voting-power',
  FLASH_LOAN_EXECUTE: '/flash-loan/execute',
  STAKING_INFO: '/staking/info',
  STAKING_POSITION: '/staking/position',
  STAKING_STAKE: '/staking/stake',
  STAKING_UNSTAKE: '/staking/unstake',
  STAKING_CLAIM: '/staking/claim',
  ANALYTICS_OVERVIEW: '/analytics/overview',
  ANALYTICS_HISTORY: '/analytics/history',
  ADMIN_PAUSE: '/admin/pause',
  ADMIN_RESUME: '/admin/resume',
  ADMIN_CONFIG: '/admin/config',
  // Attestation & Composite Credit
  ATTESTATIONS: '/credit/attestations',
  ATTESTATION_SUBMIT: '/credit/attestations/submit',
  ATTESTATION_REVOKE: (id: string) => `/credit/attestations/${id}`,
  COMPOSITE_SCORE: '/credit/composite-score',
  COMPOSITE_SIMULATE: '/credit/composite-score/simulate',
  // Productive Lending
  PRODUCTIVE_PROJECTS: '/productive/projects',
  PRODUCTIVE_PROJECT_DETAIL: (id: string) => `/productive/projects/${id}`,
  PRODUCTIVE_PROJECT_STATUS: (id: string) => `/productive/projects/${id}/status`,
  PRODUCTIVE_PROJECT_SUBMIT: '/productive/projects/submit',
  PRODUCTIVE_POOLS: '/productive/pools',
  PRODUCTIVE_BORROWS: '/productive/borrows',
  PRODUCTIVE_BORROW_CASHFLOW: (id: string) => `/productive/borrows/${id}/cashflow`,
  PRODUCTIVE_IOT: (id: string) => `/productive/iot/${id}`,
  PRODUCTIVE_ANALYTICS: '/productive/analytics',
  // Institutional
  INSTITUTIONAL_ONBOARD: '/institutional/onboard',
  INSTITUTIONAL_STATUS: '/institutional/status',
  INSTITUTIONAL_KYB: '/institutional/kyb',
  INSTITUTIONAL_KYB_VERIFY: '/institutional/kyb/verify',
  INSTITUTIONAL_SUB_ACCOUNTS: '/institutional/sub-accounts',
  INSTITUTIONAL_API_KEYS: '/institutional/api-keys',
  INSTITUTIONAL_API_KEY_CREATE: '/institutional/api-keys',
  INSTITUTIONAL_API_KEY_REVOKE: (id: string) => `/institutional/api-keys/${id}`,
  INSTITUTIONAL_BULK: '/institutional/bulk',
  INSTITUTIONAL_BULK_OPERATIONS: '/institutional/bulk-operations',
  // Privacy
  PRIVACY_CONFIG: '/privacy/config',
  PRIVACY_LEVEL: '/privacy/level',
  PRIVACY_DISCLOSURES: '/privacy/disclosures',
  PRIVACY_DISCLOSURE_ADD: '/privacy/disclosures',
  PRIVACY_DISCLOSURE_REMOVE: (id: string) => `/privacy/disclosures/${id}`,
  PRIVACY_CHECK_ACCESS: '/privacy/check-access',
  PRIVACY_AUDIT_LOG: '/privacy/audit-log',
  // Advanced Sec-Lending
  SEC_LENDING_FRACTIONAL: '/sec-lending/fractional',
  FRACTIONAL_OFFERS: '/sec-lending/fractional-offers',
  FRACTIONAL_ACCEPT: (id: string) => `/sec-lending/fractional-offers/${id}/accept`,
  SEC_LENDING_NETTING: '/sec-lending/netting',
  NETTING_PROPOSE: '/sec-lending/netting/propose',
  SEC_LENDING_NETTING_PROPOSE: '/sec-lending/netting/propose',
  NETTING_EXECUTE: (id: string) => `/sec-lending/netting/${id}/execute`,
  SEC_LENDING_NETTING_EXECUTE: (id: string) => `/sec-lending/netting/${id}/execute`,
  CORPORATE_ACTION_PROCESS: (id: string) => `/sec-lending/corporate-actions/${id}/process`,
  // Wallet
  WALLET_CONNECT: '/wallet/connect',
  WALLET_DISCONNECT: '/wallet/disconnect',
  WALLET_CONNECTIONS: '/wallet/connections',
  WALLET_CONNECTION_PRIMARY: (id: string) => `/wallet/connections/${id}/primary`,
  WALLET_PREFERENCES: '/wallet/preferences',
  WALLET_TRANSACTION_SUBMIT: '/wallet/transaction/submit',
  WALLET_TRANSACTION_SIGN: (id: string) => `/wallet/transaction/${id}/sign`,
  WALLET_TRANSACTION_STATUS: (id: string) => `/wallet/transaction/${id}`,
  WALLET_TRANSACTIONS: '/wallet/transactions',
  WALLET_PARTY_MAPPINGS: '/wallet/party-mappings',
  // Notifications
  NOTIFICATIONS: '/notifications',
  NOTIFICATIONS_UNREAD_COUNT: '/notifications/unread-count',
  NOTIFICATION_READ: (id: string) => `/notifications/${id}/read`,
  NOTIFICATION_DELETE: (id: string) => `/notifications/${id}`,
  NOTIFICATIONS_READ_ALL: '/notifications/read-all',
  NOTIFICATION_PREFERENCES: '/notifications/preferences',
  NOTIFICATION_PREFERENCES_TEST: '/notifications/preferences/test',
  // Webhooks
  WEBHOOKS: '/webhooks',
  WEBHOOK_DETAIL: (id: string) => `/webhooks/${id}`,
  WEBHOOK_TEST: (id: string) => `/webhooks/${id}/test`,
  WEBHOOK_DELIVERIES: (id: string) => `/webhooks/${id}/deliveries`,
  // Auth — Security (MP22)
  AUTH_CSRF_TOKEN: '/auth/csrf-token',
  AUTH_SESSIONS: '/auth/sessions',
  AUTH_REVOKE_ALL_SESSIONS: '/auth/revoke-all-sessions',
  // Compliance — KYC (MP21)
  COMPLIANCE_KYC_INITIATE: '/compliance/kyc/initiate',
  COMPLIANCE_KYC_STATUS: '/compliance/kyc/status',
  COMPLIANCE_KYC_HISTORY: '/compliance/kyc/history',
  COMPLIANCE_KYC_RETRY: '/compliance/kyc/retry',
  // Compliance — AML (MP21)
  COMPLIANCE_AML_STATUS: '/compliance/aml/status',
  COMPLIANCE_AML_SCREENINGS: '/compliance/aml/screenings',
  // Compliance — GDPR (MP21)
  COMPLIANCE_GDPR_EXPORT: '/compliance/data-export',
  COMPLIANCE_GDPR_DELETE: '/compliance/data-deletion',
  COMPLIANCE_GDPR_STATUS: '/compliance/data-deletion/status',
} as const;
