export const ENDPOINTS = {
  POOLS: '/pools',
  POOL_DETAIL: (id: string) => `/pools/${id}`,
  POOL_HISTORY: (id: string) => `/pools/${id}/history`,
  POOL_DEPOSIT: (id: string) => `/pools/${id}/deposit`,
  POOL_WITHDRAW: (id: string) => `/pools/${id}/withdraw`,
  BORROW_REQUEST: '/borrow/request',
  BORROW_POSITIONS: '/borrow/positions',
  BORROW_REPAY: (id: string) => `/borrow/positions/${id}/repay`,
  BORROW_ADD_COLLATERAL: (id: string) => `/borrow/positions/${id}/add-collateral`,
  SEC_LENDING_OFFERS: '/sec-lending/offers',
  SEC_LENDING_ACCEPT: (id: string) => `/sec-lending/offers/${id}/accept`,
  SEC_LENDING_DEALS: '/sec-lending/deals',
  SEC_LENDING_RECALL: (id: string) => `/sec-lending/deals/${id}/recall`,
  SEC_LENDING_RETURN: (id: string) => `/sec-lending/deals/${id}/return`,
  CREDIT_SCORE: '/credit/score',
  CREDIT_HISTORY: '/credit/history',
  ORACLE_PRICES: '/oracle/prices',
  ORACLE_PRICE: (asset: string) => `/oracle/prices/${asset}`,
  GOVERNANCE_PROPOSALS: '/governance/proposals',
  GOVERNANCE_VOTE: (id: string) => `/governance/proposals/${id}/vote`,
  FLASH_LOAN_EXECUTE: '/flash-loan/execute',
  STAKING_INFO: '/staking/info',
  STAKING_POSITION: '/staking/position',
  STAKING_STAKE: '/staking/stake',
  STAKING_UNSTAKE: '/staking/unstake',
  STAKING_CLAIM: '/staking/claim',
  ANALYTICS_OVERVIEW: '/analytics/overview',
  ANALYTICS_HISTORY: '/analytics/history',
  ADMIN_PAUSE: '/admin/pause',
  ADMIN_RESUME: '/admin/resume',
  ADMIN_CONFIG: '/admin/config',
  // Attestation & Composite Credit
  ATTESTATIONS: '/attestations',
  ATTESTATION_SUBMIT: '/attestations/submit',
  ATTESTATION_REVOKE: (id: string) => `/attestations/${id}/revoke`,
  COMPOSITE_SCORE: '/credit/composite',
  COMPOSITE_SIMULATE: '/credit/composite/simulate',
  // Productive Lending
  PRODUCTIVE_PROJECTS: '/productive/projects',
  PRODUCTIVE_PROJECT_DETAIL: (id: string) => `/productive/projects/${id}`,
  PRODUCTIVE_PROJECT_SUBMIT: '/productive/projects/submit',
  PRODUCTIVE_POOLS: '/productive/pools',
  PRODUCTIVE_BORROWS: '/productive/borrows',
  PRODUCTIVE_IOT: (id: string) => `/productive/projects/${id}/iot`,
  // Institutional
  INSTITUTIONAL_STATUS: '/institutional/status',
  INSTITUTIONAL_ONBOARD: '/institutional/onboard',
  INSTITUTIONAL_KYB: '/institutional/kyb',
  INSTITUTIONAL_API_KEYS: '/institutional/api-keys',
  INSTITUTIONAL_API_KEY_CREATE: '/institutional/api-keys',
  INSTITUTIONAL_API_KEY_REVOKE: (id: string) => `/institutional/api-keys/${id}/revoke`,
  INSTITUTIONAL_BULK_OPERATIONS: '/institutional/bulk-operations',
  // Privacy
  PRIVACY_CONFIG: '/privacy/config',
  PRIVACY_LEVEL: '/privacy/level',
  PRIVACY_DISCLOSURES: '/privacy/disclosures',
  PRIVACY_DISCLOSURE_ADD: '/privacy/disclosures',
  PRIVACY_DISCLOSURE_REMOVE: (id: string) => `/privacy/disclosures/${id}`,
  PRIVACY_AUDIT_LOG: '/privacy/audit-log',
  // Advanced Sec-Lending
  SEC_LENDING_FRACTIONAL: '/sec-lending/fractional',
  SEC_LENDING_NETTING: '/sec-lending/netting',
  SEC_LENDING_NETTING_PROPOSE: '/sec-lending/netting/propose',
  SEC_LENDING_NETTING_EXECUTE: (id: string) => `/sec-lending/netting/${id}/execute`,
} as const;
